# Sensor type mappings with their parameters, message types and frequencies
# Following the options from the main page?
# https://ardupilot.org/copter/docs/common-optional-hardware.html
sensors:
# Case study testing
  # Rangefinder bug
  CS1:
    parameters:
      PRX_TYPE: 2
    msg_type:
      - OBSTACLE_DISTANCE_3D
    frequency: [25]
    # <field type="uint32_t" name="time_boot_ms" units="ms">Timestamp (time since system boot).</field>
    # <field type="uint8_t" name="sensor_type" enum="MAV_DISTANCE_SENSOR">Class id of the distance sensor type.</field>
    # <field type="uint8_t" name="frame" enum="MAV_FRAME">Coordinate frame of reference.</field>
    # <field type="uint16_t" name="obstacle_id" instance="true"> Unique ID given to each obstacle so that its movement can be tracked. Use UINT16_MAX if object ID is unknown or cannot be determined.</field>
    # <field type="float" name="x" units="m"> X position of the obstacle.</field>
    # <field type="float" name="y" units="m"> Y position of the obstacle.</field>
    # <field type="float" name="z" units="m"> Z position of the obstacle.</field>
    # <field type="float" name="min_distance" units="m">Minimum distance the sensor can measure.</field>
    # <field type="float" name="max_distance" units="m">Maximum distance the sensor can measure.</field>
    default_msg: [time, 0, 12, 65535, 11, 11, 11, 0, 12]
  # Mount bug (no mount value)
  CS2:
    parameters:
    msg_type:
      - MAV_CMD_DO_MOUNT_CONTROL
    # <param index="1" label="Pitch">pitch depending on mount mode (degrees or degrees/second depending on pitch input).</param>
    # <param index="2" label="Roll">roll depending on mount mode (degrees or degrees/second depending on roll input).</param>
    # <param index="3" label="Yaw">yaw depending on mount mode (degrees or degrees/second depending on yaw input).</param>
    # <param index="4" label="Altitude" units="m">altitude depending on mount mode.</param>
    # <param index="5" label="Latitude">latitude, set if appropriate mount mode.</param>
    # <param index="6" label="Longitude">longitude, set if appropriate mount mode.</param>
    # <param index="7" label="Mode" enum="MAV_MOUNT_MODE">Mount mode.</param>
 
    frequency: [-1]
  # Mount bug (incorrect yaw)
  CS3:
    parameters:
      MNT_TYPE: 4
    msg_type:
      - MAV_CMD_DO_MOUNT_CONTROL
    frequency: [-1]
    calibration_msg: [0,0,0,0,0,0,2]
  # ADSB bug
  CS4:
    parameters:
    msg_type:
      - SET_ATTITUDE_TARGET
    # <field type="uint32_t" name="time_boot_ms" units="ms">Timestamp (time since system boot).</field>
    # <field type="uint8_t" name="target_system">System ID</field>
    # <field type="uint8_t" name="target_component">Component ID</field>
    # <field type="uint8_t" name="type_mask" enum="ATTITUDE_TARGET_TYPEMASK" display="bitmask">Bitmap to indicate which dimensions should be ignored by the vehicle.</field>
    # <field type="float[4]" name="q">Attitude quaternion (w, x, y, z order, zero-rotation is 1, 0, 0, 0) from MAV_FRAME_LOCAL_NED to MAV_FRAME_BODY_FRD</field>
    # <field type="float" name="body_roll_rate" units="rad/s">Body roll rate</field>
    # <field type="float" name="body_pitch_rate" units="rad/s">Body pitch rate</field>
    # <field type="float" name="body_yaw_rate" units="rad/s">Body yaw rate</field>
    # <field type="float" name="thrust">Collective thrust, normalized to 0 .. 1 (-1 .. 1 for vehicles capable of reverse trust)</field>
    frequency: [-1]
    calibration_msg: [time,0,0,0,[0,0,0,0],0,0,0,0]
  # GPS YAW
  CS5:
    parameters:
    msg_type:
  # Notch filter
  CS6:
    parameters:
    AHRS_EKF_TYPE": 10,
    INS_LOG_BAT_MASK": 3,
    INS_LOG_BAT_OPT": 4,
    INS_GYRO_FILTER": 100, # set the gyro filter high so we can observe behaviour
    LOG_BITMASK": 65535,
    LOG_DISARMED": 0,
    INS_HNTCH_ENABLE: 1,
    INS_HNTCH_FREQ: 120,
    INS_HNTCH_REF: 1.0,
    INS_HNTCH_HMNCS: 3,  # First and second harmonic
    INS_HNTCH_ATT: 50,
    INS_HNTCH_BW: 40,
    INS_HNTCH_MODE: 0,  # Static notch
    msg_type:

# Generic (Set of 8 peripherals to test)
  ADSB:
    parameters:
      ADSB_TYPE: 1
      AVD_ENABLE: 1
    msg_type:
      - ADSB_VEHICLE
    frequency: [-1]

  OpticalFlow:
    parameters:
      FLOW_TYPE: 5
    frequency: [-1, -1, -1]
    msg_type:
      - OPTICAL_FLOW
      - OPTICAL_FLOW_RAD
      - HIL_OPTICAL_FLOW

  Gimbal:
    # cmd_msgs: True
    parameters:
      MNT_TYPE: 4
    msg_type:
    - GIMBAL_CONTROL
    - GIMBAL_DEVICE_ATTITUDE_STATUS
    - GIMBAL_DEVICE_INFORMATION
    - GIMBAL_MANAGER_SET_ATTITUDE
    - GIMBAL_MANAGER_SET_PITCHYAW
    frequency: [-1,-1,-1,-1,-1]

  Camera:
    parameters:
      CAM1_TYPE: 5
    msg_type:
    - DIGICAM_CONTROL

  AP_Mount:
    parameters:
      MNT_TYPE: 4
    msg_type:
      - MAV_CMD_DO_MOUNT_CONTROL
      - MAV_CMD_DO_MOUNT_CONTROL_QUAT
      - MAV_CMD_DO_MOUNT_CONFIGURE
    frequency: [-1]

  Visual_ODOM:
    parameters:
      VISO_TYPE: 1
    msg_type:
      - ATT_POS_MOCAP
      - VICON_POSITION_ESTIMATE
      - VISION_POSITION_DELTA
      - VISION_POSITION_ESTIMATE
      - VISION_SPEED_ESTIMATE
    frequency: [30]
    default_msg: [time, [0,0,0,0], 0, 0, 0]

  EFI:
    parameters:
      EFI_TYPE: 9
    msg_type:
      - EFI_STATUS
    frequency: [-1]

  GPS:
    parameters:
      GPS1_TYPE: 14
    msg_type:
      # - GPS_INJECT_DATA (Dep)
      - GPS_INPUT
      # - GPS_RAW_INT
      # - GPS_RTCM_DATA (To support)
      # HIL_GPS will mostly not work with this?
    frequency: [5]
    # Copied from the SITL default -> Ardupilot standard location
    default_msg: ['time', 0, 0, 1200000, 2430, 6, -353632621, 1491652374, 584, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 3.0, 3.0, 10]

  OPENDRONEID:
    msg_type: # Might not just work outside the box
      - OPEN_DRONE_ID_BASIC_ID
      - OPEN_DRONE_ID_LOCATION
      - OPEN_DRONE_ID_AUTHENTICATION
      - OPEN_DRONE_ID_SELF_ID
      - OPEN_DRONE_ID_SYSTEM
      - OPEN_DRONE_ID_OPERATOR_ID
      - OPEN_DRONE_ID_MESSAGE_PACK
      - OPEN_DRONE_ID_ARM_STATUS
      - OPEN_DRONE_ID_SYSTEM_UPDATE
    frequency: [-1]

  # TODO Verification required
  AP_ARSPD:
    parameters:
      ARSPD_ENABLE: 1
      ADSB_TYPE: 2
      ARSPD_USE: 1
    msg_type:
      - ADSB_VEHICLE
    frequency: [-1]


  # TODO Verification required
  # AP_AIS:
  #   parameters:
  #     AIS_TYPE: 1
  #   msg_type:

  Baro_Ext:
    parameters:
      ARSPD_USE: 1
    msg_type:
      - SCALED_PRESSURE2
    frequency: [10]


  # Might not work on SITL :|
  AP_CropSprayer:
    parameters:
      SPRAY_ENABLE: 1
    msg_type:
      - MAV_CMD_DO_SPRAYER
    frequency: [-1]

  # ESC?
  # Ethernet adapter?
  #


  AP_Rangefinder:
    parameters:
      PRX_TYPE: 2
    msg_type:
      - OBSTACLE_DISTANCE
      - OBSTACLE_DISTANCE_3D


  AP_Proximity:
    parameters:
      PRX_TYPE: 2
    msg_type:
      - OBSTACLE_DISTANCE_3D
    frequency: [25]
    default_msg: [time, 0, 12, 65535, 11, 11, 11, 0, 12]


  Terrain:
    msg_type:
      - TERRAIN_DATA
    frequency: [-1]

  Fence:
    msg_type:
      - FENCE_POINT
      - FENCE_FETCH_POINT
      - FENCE_STATUS
    frequency: [-1, -1, -1]

  OSD:
    msg_type:
      - OSD_PARAM_SHOW_CONFIG
      - OSD_PARAM_CONFIG_REPLY
      - OSD_PARAM_SHOW_CONFIG_REPLY
      - OSD_PARAM_CONFIG
    frequency: [-1, -1, -1, -1]

  AIS:
    parameters:
      AIS_TYPE : 1
      SERIAL1_PROTOCOL: 40
      SERIAL1_BAUD: 38
      MAV1_ADSB: 5
    msg_type:
      - AIS_VESSEL
    frequency: [-1]

  BARO_EXT:
    parameters:
      BARO_PROBE_EXT : 4
      BARO_PRIMARY: 1
    msg_type: # Might not just work outside the box
      - SCALED_PRESSURE
      - SCALED_PRESSURE2
      - SCALED_PRESSURE3
    frequency: [-1]

  AHRS_EXT:
    parameters:
      AHRS_EKF_TYPE: 11
      EAHRS_TYPE: 1
    msg_type: # Might not just work outside the box
      - AHRS
      - AHRS2
      - AHRS3
    frequency: [-1] # TODO: Check the frequency for health status

  GENERATOR:
    parameters:
      GEN_TYPE: 1
    msg_type: # Might not just work outside the box
      - GENERATOR_STATUS
    frequency: [-1]

  LANDINGGEAR:
    parameters:
      LGR_ENABLE: 1
    msg_type: # Might not just work outside the box
      - MAV_CMD_AIRFRAME_CONFIGURATION
    frequency: [-1]


generic_params:
  # Only to be enable for CS5/CS6 cases
  # - SIM_VIB_FREQ_X
  # - SIM_VIB_FREQ_Y
  # - SIM_VIB_FREQ_Z
  # - SIM_VIB_MOT_MULT
