# Sensor type mappings with their parameters, message types and frequencies
# Following the options from the main page?
# https://ardupilot.org/copter/docs/common-optional-hardware.html
sensors:
# Case study testing
  # Rangefinder bug
  CS1:
    parameters:
      PRX_TYPE: 2
    msg_type:
      - OBSTACLE_DISTANCE_3D
    frequency: [25]
    default_msg: [time, 0, 12, 65535, 11, 11, 11, 0, 12]
  # Mount bug (no mount value)
  CS2:
    parameters:
    msg_type:
      - MAV_CMD_DO_MOUNT_CONTROL
    frequency: [-1]
    calibration_msg: [0,0,0,0,0,0,2]
  # Mount bug (incorrect yaw)
  CS3:
    parameters:
      MNT_TYPE: 4
    msg_type:
      - MAV_CMD_DO_MOUNT_CONTROL
    frequency: [-1]
  # ADSB bug
  CS4:
    parameters:
    msg_type:
      - SET_ATTITUDE_TARGET
    frequency: [-1]
  # GPS YAW
  CS5:
    parameters:
    msg_type:
# Generic
  AP_ADSB:
    parameters:
      ADSB_TYPE: 1
      # AVD_ENABLE: 1 # To actually use the ADSB to do avoidance?
    msg_type:
      - ADSB_VEHICLE
    frequency: [-1]

  # TODO Verification required
  AP_ARSPD:
    parameters:
      ARSPD_ENABLE: 1
      ADSB_TYPE: 2
      ARSPD_USE: 1
    msg_type:
      - ADSB_VEHICLE
    frequency: [-1]

  # TODO Verification required
  # AP_AIS:
  #   parameters:
  #     AIS_TYPE: 1
  #   msg_type:

  Baro_Ext:
    parameters:
      ARSPD_USE: 1
    msg_type:
      - SCALED_PRESSURE2
    frequency: [10]

  # Button INPUT
  # Buzzer

  AP_Gimbal:
    # cmd_msgs: True
    parameters:
      MNT_TYPE: 4
    msg_type:
      - MAV_CMD_DO_MOUNT_CONTROL
    frequency: [-1]

  AP_Mount:
    parameters:
      MNT_TYPE: 4
    msg_type:
      - MAV_CMD_DO_MOUNT_CONTROL
    frequency: [-1]

  # Might not work on SITL :|
  AP_CropSprayer:
    parameters:
      SPRAY_ENABLE: 1
    msg_type:
      - MAV_CMD_DO_SPRAYER
    frequency: [-1]

  # ESC?
  # Ethernet adapter?
  #

  OpticalFlow:
    parameters:
      FLOW_TYPE: 5
    frequency: [-1, -1, -1]
    msg_type:
      - OPTICAL_FLOW
      - OPTICAL_FLOW_RAD
      - HIL_OPTICAL_FLOW

  AP_Rangefinder:
    parameters:
      RNGFND_TYPE: 5
    msg_type:
      - DISTANCE_SENSOR

  AP_EFI:
    parameters:
      EFI_TYPE: 9
    msg_type:
      - EFI_STATUS

  AP_Proximity:
    parameters:
      PRX_TYPE: 2
    msg_type:
      - OBSTACLE_DISTANCE_3D
    frequency: [25]
    default_msg: [time, 0, 12, 65535, 11, 11, 11, 0, 12]

  GPS:
    parameters:
      MNT_TYPE: 4
    msg_type:
      - GPS_RAW_INT
      - GPS_STATUS
      - SET_GPS_GLOBAL_ORIGIN
      - GPS_GLOBAL_ORIGIN
      - HIL_GPS
      - GPS_INJECT_DATA
      - GPS2_RAW
      - GPS_RKT
      - GPS_INPUT
      - GPS_RTCM_DATA
      - GPS2_RKT
    frequency: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1]

  Terrain:
    msg_type:
      - TERRAIN_DATA
    frequency: [-1]

  Fence:
    msg_type:
      - FENCE_POINT
      - FENCE_FETCH_POINT
      - FENCE_STATUS
    frequency: [-1, -1, -1]

  OSD:
    msg_type:
      - OSD_PARAM_SHOW_CONFIG
      - OSD_PARAM_CONFIG_REPLY
      - OSD_PARAM_SHOW_CONFIG_REPLY
      - OSD_PARAM_CONFIG
    frequency: [-1, -1, -1, -1]

  OpenDroneID:
    msg_type:
      - OSD_PARAM_SHOW_CONFIG
      - OSD_PARAM_CONFIG_REPLY
      - OSD_PARAM_SHOW_CONFIG_REPLY
      - OSD_PARAM_CONFIG
    frequency: [-1, -1, -1, -1]

generic_params:
  - SIM_GPS_DISABLE
